remote_theme: MicrosoftLearning/Jekyll-Theme
exclude:
  - readme.md
  - .github/
header_pages:
  - index.html
author: Microsoft Learning
twitter_username: mslearning
github_username: MicrosoftLearning
title: DevOps and Platform Engineering
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
markdown: GFM
